# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sumadorVector_pb2 as sumadorVector__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sumadorVector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CentroCalculoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SumarVector = channel.unary_unary(
                '/sumadorVector.CentroCalculo/SumarVector',
                request_serializer=sumadorVector__pb2.VectorRequest.SerializeToString,
                response_deserializer=sumadorVector__pb2.SumaResponse.FromString,
                _registered_method=True)


class CentroCalculoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SumarVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CentroCalculoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SumarVector': grpc.unary_unary_rpc_method_handler(
                    servicer.SumarVector,
                    request_deserializer=sumadorVector__pb2.VectorRequest.FromString,
                    response_serializer=sumadorVector__pb2.SumaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sumadorVector.CentroCalculo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sumadorVector.CentroCalculo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CentroCalculo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SumarVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sumadorVector.CentroCalculo/SumarVector',
            sumadorVector__pb2.VectorRequest.SerializeToString,
            sumadorVector__pb2.SumaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class Operador1Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SumarParcial = channel.unary_unary(
                '/sumadorVector.Operador1/SumarParcial',
                request_serializer=sumadorVector__pb2.SumaParcialRequest.SerializeToString,
                response_deserializer=sumadorVector__pb2.SumaParcialResponse.FromString,
                _registered_method=True)


class Operador1Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def SumarParcial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Operador1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SumarParcial': grpc.unary_unary_rpc_method_handler(
                    servicer.SumarParcial,
                    request_deserializer=sumadorVector__pb2.SumaParcialRequest.FromString,
                    response_serializer=sumadorVector__pb2.SumaParcialResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sumadorVector.Operador1', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sumadorVector.Operador1', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Operador1(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SumarParcial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sumadorVector.Operador1/SumarParcial',
            sumadorVector__pb2.SumaParcialRequest.SerializeToString,
            sumadorVector__pb2.SumaParcialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class Operador2Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SumarFinal = channel.unary_unary(
                '/sumadorVector.Operador2/SumarFinal',
                request_serializer=sumadorVector__pb2.SumaFinalRequest.SerializeToString,
                response_deserializer=sumadorVector__pb2.SumaResponse.FromString,
                _registered_method=True)


class Operador2Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def SumarFinal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Operador2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SumarFinal': grpc.unary_unary_rpc_method_handler(
                    servicer.SumarFinal,
                    request_deserializer=sumadorVector__pb2.SumaFinalRequest.FromString,
                    response_serializer=sumadorVector__pb2.SumaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sumadorVector.Operador2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sumadorVector.Operador2', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Operador2(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SumarFinal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sumadorVector.Operador2/SumarFinal',
            sumadorVector__pb2.SumaFinalRequest.SerializeToString,
            sumadorVector__pb2.SumaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
